language: python
python:
  - "3.6"
<<<<<<< HEAD
=======
r
>>>>>>> master
install:
  - pip install -r requirements.txt
script:
  - pytest
<<<<<<< HEAD
branches:
  only:
  - develop
  - master
=======

branches:
  only:
   - develop
   - master
>>>>>>> master
